version: '3'
services:
    nmap:
        image: raesene/alpine-nmap
        network_mode: "host"
    dirb:
        build: ../../Dockerfiles/dirb
        network_mode: "host"
    wpscan:
        image: wpscanteam/wpscan
        network_mode: "host"
    weevely:
        build: ../../Dockerfiles/weevely
        network_mode: "host"
    nikto:
        image: k0st/alpine-nikto
        network_mode: "host"
    sqlmap:
        image: k0st/alpine-sqlmap
        network_mode: "host"
